[package]
name = "server"
version = "0.1.0"
authors = ["Ryan P. Brewster <RyanPBrewster@gmail.com>"]
edition = "2018"

[dependencies]
env_logger = "0.7"
log   = "0.4"
prost = "0.6"
tokio = { version = "0.2", features = ["macros"] }
tonic = "0.1"

[build-dependencies]
tonic-build = "0.1"
